[package]
name = "nss_dnsoverhttps"
version = "0.1.0"
authors = ["Jan-Erik Rediger <janerik@fnordig.de>"]

[lib]
crate-type = [ "cdylib" ]

[dependencies]
dnsoverhttps = "0.1.0"

[build-dependencies]
cc = "1.0"

[profile.release]
lto = true
panic = "abort"
